In [81]:
import numpy as np

# Define the data type for each column
dt = np.dtype([('col1', 'U9'), ('col2', 'U9'), ('col3', 'U9'), ('col4', 'U9'), ('col5', 'U9'), ('col6', 'U9'), ('col7', 'U9')])

# Load the data from the text file
data = np.loadtxt('weather_data_nyc_centralpark_2016(1).txt', delimiter='\t', dtype=dt)

# Access the data 
col1 = data['col1']
col2 = data['col2']
col3 = data['col3']
col4 = data['col4']
col5 = data['col5']
col6 = data['col6']
col7 = data['col7']

In [82]:
col1

array(['date', '01-01-16', '02-01-16', '03-01-16', '04-01-16', '05-01-16',
       '06-01-16', '07-01-16', '08-01-16', '09-01-16', '10-01-16',
       '11-01-16', '12-01-16', '13-01-16', '14-01-16', '15-01-16',
       '16-01-16', '17-01-16', '18-01-16', '19-01-16', '20-01-16',
       '21-01-16', '22-01-16', '23-01-16', '24-01-16', '25-01-16',
       '26-01-16', '27-01-16', '28-01-16', '29-01-16', '30-01-16',
       '31-01-16', '01-02-16', '02-02-16', '03-02-16', '04-02-16',
       '05-02-16', '06-02-16', '07-02-16', '08-02-16', '09-02-16',
       '10-02-16', '11-02-16', '12-02-16', '13-02-16', '14-02-16',
       '15-02-16', '16-02-16', '17-02-16', '18-02-16', '19-02-16',
       '20-02-16', '21-02-16', '22-02-16', '23-02-16', '24-02-16',
       '25-02-16', '26-02-16', '27-02-16', '28-02-16', '29-02-16',
       '01-03-16', '02-03-16', '03-03-16', '04-03-16', '05-03-16',
       '06-03-16', '07-03-16', '08-03-16', '09-03-16', '10-03-16',
       '11-03-16', '12-03-16', '13-03-16', '14-03-16', '15-03-16',
       '16-03-16', '17-03-16', '18-03-16', '19-03-16', '20-03-16',
       '21-03-16', '22-03-16', '23-03-16', '24-03-16', '25-03-16',
       '26-03-16', '27-03-16', '28-03-16', '29-03-16', '30-03-16',
       '31-03-16', '01-04-16', '02-04-16', '03-04-16', '04-04-16',
       '05-04-16', '06-04-16', '07-04-16', '08-04-16', '09-04-16',
       '10-04-16', '11-04-16', '12-04-16', '13-04-16', '14-04-16',
       '15-04-16', '16-04-16', '17-04-16', '18-04-16', '19-04-16',
       '20-04-16', '21-04-16', '22-04-16', '23-04-16', '24-04-16',
       '25-04-16', '26-04-16', '27-04-16', '28-04-16', '29-04-16',
       '30-04-16', '01-05-16', '02-05-16', '03-05-16', '04-05-16',
       '05-05-16', '06-05-16', '07-05-16', '08-05-16', '09-05-16',
       '10-05-16', '11-05-16', '12-05-16', '13-05-16', '14-05-16',
       '15-05-16', '16-05-16', '17-05-16', '18-05-16', '19-05-16',
       '20-05-16', '21-05-16', '22-05-16', '23-05-16', '24-05-16',
       '25-05-16', '26-05-16', '27-05-16', '28-05-16', '29-05-16',
       '30-05-16', '31-05-16', '01-06-16', '02-06-16', '03-06-16',
       '04-06-16', '05-06-16', '06-06-16', '07-06-16', '08-06-16',
       '09-06-16', '10-06-16', '11-06-16', '12-06-16', '13-06-16',
       '14-06-16', '15-06-16', '16-06-16', '17-06-16', '18-06-16',
       '19-06-16', '20-06-16', '21-06-16', '22-06-16', '23-06-16',
       '24-06-16', '25-06-16', '26-06-16', '27-06-16', '28-06-16',
       '29-06-16', '30-06-16', '01-07-16', '02-07-16', '03-07-16',
       '04-07-16', '05-07-16', '06-07-16', '07-07-16', '08-07-16',
       '09-07-16', '10-07-16', '11-07-16', '12-07-16', '13-07-16',
       '14-07-16', '15-07-16', '16-07-16', '17-07-16', '18-07-16',
       '19-07-16', '20-07-16', '21-07-16', '22-07-16', '23-07-16',
       '24-07-16', '25-07-16', '26-07-16', '27-07-16', '28-07-16',
       '29-07-16', '30-07-16', '31-07-16', '01-08-16', '02-08-16',
       '03-08-16', '04-08-16', '05-08-16', '06-08-16', '07-08-16',
       '08-08-16', '09-08-16', '10-08-16', '11-08-16', '12-08-16',
       '13-08-16', '14-08-16', '15-08-16', '16-08-16', '17-08-16',
       '18-08-16', '19-08-16', '20-08-16', '21-08-16', '22-08-16',
       '23-08-16', '24-08-16', '25-08-16', '26-08-16', '27-08-16',
       '28-08-16', '29-08-16', '30-08-16', '31-08-16', '01-09-16',
       '02-09-16', '03-09-16', '04-09-16', '05-09-16', '06-09-16',
       '07-09-16', '08-09-16', '09-09-16', '10-09-16', '11-09-16',
       '12-09-16', '13-09-16', '14-09-16', '15-09-16', '16-09-16',
       '17-09-16', '18-09-16', '19-09-16', '20-09-16', '21-09-16',
       '22-09-16', '23-09-16', '24-09-16', '25-09-16', '26-09-16',
       '27-09-16', '28-09-16', '29-09-16', '30-09-16', '01-10-16',
       '02-10-16', '03-10-16', '04-10-16', '05-10-16', '06-10-16',
       '07-10-16', '08-10-16', '09-10-16', '10-10-16', '11-10-16',
       '12-10-16', '13-10-16', '14-10-16', '15-10-16', '16-10-16',
       '17-10-16', '18-10-16', '19-10-16', '20-10-16', '21-10-16',
       '22-10-16', '23-10-16', '24-10-16', '25-10-16', '26-10-16',
       '27-10-16', '28-10-16', '29-10-16', '30-10-16', '31-10-16',
       '01-11-16', '02-11-16', '03-11-16', '04-11-16', '05-11-16',
       '06-11-16', '07-11-16', '08-11-16', '09-11-16', '10-11-16',
       '11-11-16', '12-11-16', '13-11-16', '14-11-16', '15-11-16',
       '16-11-16', '17-11-16', '18-11-16', '19-11-16', '20-11-16',
       '21-11-16', '22-11-16', '23-11-16', '24-11-16', '25-11-16',
       '26-11-16', '27-11-16', '28-11-16', '29-11-16', '30-11-16',
       '01-12-16', '02-12-16', '03-12-16', '04-12-16', '05-12-16',
       '06-12-16', '07-12-16', '08-12-16', '09-12-16', '10-12-16',
       '11-12-16', '12-12-16', '13-12-16', '14-12-16', '15-12-16',
       '16-12-16', '17-12-16', '18-12-16', '19-12-16', '20-12-16',
       '21-12-16', '22-12-16', '23-12-16', '24-12-16', '25-12-16',
       '26-12-16', '27-12-16', '28-12-16', '29-12-16', '30-12-16',
       '31-12-16'], dtype='<U9')

In [83]:
col2

array(['maximum t', '42', '40', '45', '36', '29', '41', '46', '46', '47',
       '59', '40', '44', '30', '38', '51', '52', '42', '31', '28', '37',
       '36', '30', '27', '35', '39', '48', '47', '42', '41', '39', '56',
       '59', '50', '59', '59', '44', '40', '47', '39', '36', '39', '31',
       '27', '22', '15', '35', '54', '39', '36', '39', '61', '55', '52',
       '40', '60', '61', '39', '41', '60', '61', '52', '55', '36', '39',
       '41', '44', '60', '67', '77', '79', '68', '59', '62', '51', '57',
       '65', '63', '57', '46', '43', '50', '56', '71', '55', '72', '55',
       '55', '62', '53', '56', '73', '79', '61', '50', '45', '43', '48',
       '58', '50', '43', '50', '65', '59', '58', '62', '65', '68', '75',
       '82', '73', '69', '73', '79', '71', '68', '69', '60', '62', '59',
       '58', '65', '51', '60', '56', '52', '57', '54', '60', '66', '72',
       '63', '76', '80', '65', '73', '59', '66', '64', '68', '73', '76',
       '66', '70', '78', '73', '88', '90', '87', '92', '87', '82', '85',
       '83', '78', '70', '83', '71', '83', '85', '67', '71', '77', '88',
       '83', '74', '79', '85', '74', '78', '87', '88', '84', '87', '86',
       '83', '84', '86', '87', '83', '76', '83', '85', '79', '76', '78',
       '84', '86', '91', '89', '86', '72', '80', '81', '82', '85', '88',
       '88', '90', '89', '93', '83', '85', '90', '94', '96', '94', '93',
       '89', '91', '95', '85', '84', '78', '80', '79', '80', '81', '83',
       '87', '86', '86', '87', '86', '91', '93', '96', '94', '92', '87',
       '85', '85', '88', '83', '86', '79', '82', '88', '86', '90', '89',
       '89', '91', '86', '89', '79', '81', '75', '80', '84', '80', '85',
       '89', '91', '90', '83', '78', '83', '91', '74', '73', '77', '82',
       '76', '82', '84', '86', '87', '71', '70', '74', '74', '69', '64',
       '59', '62', '63', '72', '69', '67', '73', '75', '68', '65', '64',
       '63', '66', '67', '62', '65', '69', '81', '81', '85', '70', '69',
       '57', '61', '62', '52', '51', '55', '51', '64', '76', '54', '58',
       '70', '72', '61', '62', '59', '53', '66', '59', '56', '63', '50',
       '61', '62', '56', '61', '61', '64', '63', '42', '41', '41', '45',
       '48', '54', '50', '50', '52', '60', '58', '54', '51', '47', '47',
       '49', '46', '46', '45', '39', '35', '35', '46', '43', '42', '34',
       '27', '39', '58', '31', '33', '40', '49', '47', '47', '50', '50',
       '60', '40', '46', '40', '44'], dtype='<U9')

In [84]:
col3

array(['minimum t', '34', '32', '35', '14', '11', '25', '31', '31', '40',
       '40', '26', '25', '22', '22', '34', '42', '30', '18', '16', '27',
       '26', '21', '24', '20', '28', '38', '34', '32', '30', '28', '36',
       '44', '38', '42', '44', '31', '30', '33', '28', '27', '31', '18',
       '15', '6', '-1', '13', '35', '35', '27', '24', '39', '44', '38',
       '35', '36', '37', '27', '26', '38', '47', '39', '29', '26', '30',
       '28', '32', '36', '47', '44', '63', '48', '40', '50', '40', '44',
       '48', '45', '42', '36', '32', '32', '35', '48', '44', '44', '38',
       '43', '42', '40', '37', '49', '61', '49', '34', '29', '26', '30',
       '48', '40', '36', '31', '43', '45', '40', '43', '42', '43', '44',
       '51', '55', '49', '49', '62', '54', '47', '50', '47', '46', '48',
       '45', '46', '45', '45', '51', '48', '46', '48', '48', '49', '52',
       '50', '50', '56', '57', '56', '46', '43', '52', '52', '54', '53',
       '54', '52', '56', '58', '61', '69', '73', '71', '70', '68', '71',
       '66', '62', '63', '66', '65', '65', '64', '52', '54', '57', '59',
       '62', '57', '58', '62', '65', '63', '61', '66', '64', '72', '68',
       '69', '67', '64', '67', '67', '68', '67', '67', '66', '63', '64',
       '66', '69', '75', '77', '67', '65', '66', '65', '68', '71', '73',
       '79', '75', '75', '72', '73', '68', '71', '74', '80', '75', '73',
       '72', '74', '75', '69', '73', '71', '69', '68', '66', '67', '69',
       '72', '70', '71', '71', '75', '74', '73', '81', '78', '77', '78',
       '77', '72', '74', '70', '73', '65', '61', '68', '69', '75', '73',
       '72', '74', '69', '74', '69', '66', '66', '65', '65', '71', '71',
       '71', '75', '74', '67', '62', '64', '67', '61', '61', '59', '70',
       '69', '68', '68', '65', '64', '58', '54', '54', '64', '56', '57',
       '56', '56', '57', '60', '60', '53', '55', '57', '58', '51', '47',
       '46', '53', '53', '47', '45', '53', '63', '67', '65', '62', '57',
       '47', '45', '47', '43', '38', '40', '42', '39', '54', '44', '40',
       '54', '57', '47', '44', '45', '41', '41', '49', '40', '41', '37',
       '41', '46', '47', '45', '49', '44', '37', '34', '36', '37', '35',
       '38', '45', '40', '39', '38', '51', '50', '42', '40', '41', '39',
       '38', '37', '40', '35', '29', '28', '28', '34', '35', '34', '19',
       '17', '24', '31', '23', '20', '30', '37', '38', '38', '36', '33',
       '40', '34', '33', '33', '31'], dtype='<U9')

In [85]:
col4

array(['average t', '38', '36', '40', '25', '20', '33', '38.5', '38.5',
       '43.5', '49.5', '33', '34.5', '26', '30', '42.5', '47', '36',
       '24.5', '22', '32', '31', '25.5', '25.5', '27.5', '33.5', '43',
       '40.5', '37', '35.5', '33.5', '46', '51.5', '44', '50.5', '51.5',
       '37.5', '35', '40', '33.5', '31.5', '35', '24.5', '21', '14', '7',
       '24', '44.5', '37', '31.5', '31.5', '50', '49.5', '45', '37.5',
       '48', '49', '33', '33.5', '49', '54', '45.5', '42', '31', '34.5',
       '34.5', '38', '48', '57', '60.5', '71', '58', '49.5', '56', '45.5',
       '50.5', '56.5', '54', '49.5', '41', '37.5', '41', '45.5', '59.5',
       '49.5', '58', '46.5', '49', '52', '46.5', '46.5', '61', '70', '55',
       '42', '37', '34.5', '39', '53', '45', '39.5', '40.5', '54', '52',
       '49', '52.5', '53.5', '55.5', '59.5', '66.5', '64', '59', '61',
       '70.5', '62.5', '57.5', '59.5', '53.5', '54', '53.5', '51.5',
       '55.5', '48', '52.5', '53.5', '50', '51.5', '51', '54', '57.5',
       '62', '56.5', '63', '68', '61', '64.5', '52.5', '54.5', '58', '60',
       '63.5', '64.5', '60', '61', '67', '65.5', '74.5', '79.5', '80',
       '81.5', '78.5', '75', '78', '74.5', '70', '66.5', '74.5', '68',
       '74', '74.5', '59.5', '62.5', '67', '73.5', '72.5', '65.5', '68.5',
       '73.5', '69.5', '70.5', '74', '77', '74', '79.5', '77', '76',
       '75.5', '75', '77', '75', '72', '75', '76', '72.5', '69.5', '71',
       '75', '77.5', '83', '83', '76.5', '68.5', '73', '73', '75', '78',
       '80.5', '83.5', '82.5', '82', '82.5', '78', '76.5', '80.5', '84',
       '88', '84.5', '83', '80.5', '82.5', '85', '77', '78.5', '74.5',
       '74.5', '73.5', '73', '74', '76', '79.5', '78', '78.5', '79',
       '80.5', '82.5', '83', '88.5', '86', '84.5', '82.5', '81', '78.5',
       '81', '76.5', '79.5', '72', '71.5', '78', '77.5', '82.5', '81',
       '80.5', '82.5', '77.5', '81.5', '74', '73.5', '70.5', '72.5',
       '74.5', '75.5', '78', '80', '83', '82', '75', '70', '73.5', '79',
       '67.5', '67', '68', '76', '72.5', '75', '76', '75.5', '75.5',
       '64.5', '62', '64', '69', '62.5', '60.5', '57.5', '59', '60', '66',
       '64.5', '60', '64', '66', '63', '58', '55.5', '54.5', '59.5', '60',
       '54.5', '55', '61', '72', '74', '75', '66', '63', '52', '53',
       '54.5', '47.5', '44.5', '47.5', '46.5', '51.5', '65', '49', '49',
       '62', '64.5', '54', '53', '52', '47', '53.5', '54', '48', '52',
       '43.5', '51', '54', '51.5', '53', '55', '54', '50', '38', '38.5',
       '39', '40', '43', '49.5', '45', '44.5', '45', '55.5', '54', '48',
       '45.5', '44', '43', '43.5', '41.5', '43', '40', '34', '31.5',
       '31.5', '40', '39', '38', '26.5', '22', '31.5', '44.5', '27',
       '26.5', '35', '43', '42.5', '42.5', '43', '41.5', '50', '37',
       '39.5', '36.5', '37.5'], dtype='<U9')

In [86]:
col5

array(['precipita', '0', '0', '0', '0', '0', '0', '0', '0', 'T', '1.8',
       '0', '0', '0', '0', 'T', '0.24', '0.05', 'T', '0', '0', '0',
       '0.01', '2.31', 'T', '0', '0', 'T', '0', '0', '0', '0', '0.01',
       '0', '0.73', 'T', '0.53', '0', '0', '0.05', '0', '0.01', 'T', '0',
       '0', '0', '0.44', '1.01', '0', '0', '0', '0', '0.03', '0', '0.3',
       '1.22', '0.02', '0', '0', '0', '0.05', '0', '0.14', '0', '0.11',
       '0', '0', '0', '0', '0', '0', '0.06', '0', 'T', '0.29', '0',
       '0.02', 'T', '0', '0', '0.07', '0.06', '0', '0', '0', '0.04', '0',
       '0', '0.38', '0', '0', '0', '0.02', '0.16', '0.09', '0.47', '0',
       '0', '0.09', '0.01', '0.11', '0', '0.01', '0.2', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', 'T', '0.16', '0', '0', '0.24', '0',
       '0', '0.05', '0', '0.16', '0.04', '0.61', '0.01', '0', '0.54', '0',
       '0.16', '0', '0', '0', '0', '0.25', '0', '0', '0', '0', 'T', '0',
       '0', '0.04', '0.09', '0.02', '0.18', '0', '0', '0', '0', 'T',
       '1.65', '0', '0', '0', '0.04', '0.4', '0.91', '0', 'T', '0.45',
       '0', '0', '0', '0', '0', '0', '0', '0.22', '0', '0', '0', '0', 'T',
       '0', '0', '0', '0', '0', '0.45', '0.12', '0.01', '0', '0.83', '0',
       '0', '0.49', '0.66', '0', '0.04', '0.08', '0.53', 'T', '0', '0',
       '0', '0.62', '0', 'T', '0', '0.35', '0', '0', '0', '0', '0', '0',
       '1', '0', '0', 'T', '1.09', '0.25', '1.08', 'T', '0', '0', '0',
       '0', '0.05', '0', '0', '0', '0.09', '0.15', '0.32', '0', '0.06',
       '0', '0.11', '0.01', '0.03', '0.01', '0.82', '0.31', '0', '0', '0',
       '0.01', '0', '0', '0', '0', '0', 'T', '0.5', '0', '0', '0', '0',
       'T', '0', '0', '0.22', 'T', '0', '0', '0', '0.56', '0', '0', '0',
       '0', '0.68', '0', '0', '0', '0.01', '0.2', '0', '0', '0.22', '0',
       '0', '0.4', '0', '0', '0', '0', '0', '0', '0', '0.23', '0.55', '0',
       '0', '0', 'T', '0', '0', '0', '0', '0', '0', '0', '1.11', '0.29',
       '0', 'T', '0', '0', '1.41', '0', '0', '0.56', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0.06', '0', '0', '0', '0', '0', '1.81',
       '0', '0', '0', '0.25', '0.31', '0', '0', '0', '0.03', '0.02', '0',
       '0', '0', '2.2', '0.73', '0.07', '0', 'T', '0', '0.19', '0.35',
       '0.09', '0', '0', '0', '0.03', '0.5', '0', '0', '0', '0', '0.73',
       '0.04', '0', '0', '0', '0', '0', '0.47', '0', '0.02', '0', '0',
       '0.39', '0.01', '0'], dtype='<U9')

In [87]:
col6

array(['snow fall', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       'T', '0', 'T', '0', '0', '0.4', 'T', '0', '0', '0', '0.2', '27.3',
       'T', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '2.5',
       '0', '0', '0.1', 'T', 'T', 'T', '0', '0', '0', '1.4', '0', '0',
       '0', '0', '0', '0', '0', 'T', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0.4', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', 'T', '0.5', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', 'T', 'T', '0', '0', '0', '0', 'T',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', 'T', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0.4', '0',
       '0', '0', 'T', '0', '2.8', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', 'T', '0'], dtype='<U9')

In [88]:
col7

array(['snow dept', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', 'T', 'T', 'T', '0', '0', '6', '22',
       '19', '17', '9', '6', '6', '6', '4', '2', 'T', '0', '0', '1', '0',
       '0', '0', 'T', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       'T', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', 'T', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '2', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0'], dtype='<U9')

In [89]:
import pandas as pd
data=pd.read_csv('weather_data_nyc_centralpark_2016(1).csv')
data

,date,maximum temperature,minimum temperature,average temperature,precipitation,snow fall,snow depth
0,1-1-2016,42,34,38.0,0.00,0.0,0
1,2-1-2016,40,32,36.0,0.00,0.0,0
2,3-1-2016,45,35,40.0,0.00,0.0,0
3,4-1-2016,36,14,25.0,0.00,0.0,0
4,5-1-2016,29,11,20.0,0.00,0.0,0
...,...,...,...,...,...,...,...
361,27-12-2016,60,40,50.0,0,0,0
362,28-12-2016,40,34,37.0,0,0,0
363,29-12-2016,46,33,39.5,0.39,0,0
364,30-12-2016,40,33,36.5,0.01,T,0
365,31-12-2016,44,31,37.5,0,0,0

In [90]:
import numpy as np
import pandas as pd
data=pd.read_csv('weather_data_nyc_centralpark_2016(1).csv', usecols=['date', 'average temperature'], 
                 parse_dates=['date'], index_col=['date'],squeeze=True)
keep = np.abs(data.values) < 90
filtered_data = data[keep]
filtered_data

date
2016-01-01    38.0
2016-02-01    36.0
2016-03-01    40.0
2016-04-01    25.0
2016-05-01    20.0
              ...
2016-12-27    50.0
2016-12-28    37.0
2016-12-29    39.5
2016-12-30    36.5
2016-12-31    37.5
Name: average temperature, Length: 366, dtype: float64

In [91]:
abs_temp = np.abs(data.values)
temp= abs_temp[abs_temp <90]
temp

array([38. , 36. , 40. , 25. , 20. , 33. , 38.5, 38.5, 43.5, 49.5, 33. ,
       34.5, 26. , 30. , 42.5, 47. , 36. , 24.5, 22. , 32. , 31. , 25.5,
       25.5, 27.5, 33.5, 43. , 40.5, 37. , 35.5, 33.5, 46. , 51.5, 44. ,
       50.5, 51.5, 37.5, 35. , 40. , 33.5, 31.5, 35. , 24.5, 21. , 14. ,
        7. , 24. , 44.5, 37. , 31.5, 31.5, 50. , 49.5, 45. , 37.5, 48. ,
       49. , 33. , 33.5, 49. , 54. , 45.5, 42. , 31. , 34.5, 34.5, 38. ,
       48. , 57. , 60.5, 71. , 58. , 49.5, 56. , 45.5, 50.5, 56.5, 54. ,
       49.5, 41. , 37.5, 41. , 45.5, 59.5, 49.5, 58. , 46.5, 49. , 52. ,
       46.5, 46.5, 61. , 70. , 55. , 42. , 37. , 34.5, 39. , 53. , 45. ,
       39.5, 40.5, 54. , 52. , 49. , 52.5, 53.5, 55.5, 59.5, 66.5, 64. ,
       59. , 61. , 70.5, 62.5, 57.5, 59.5, 53.5, 54. , 53.5, 51.5, 55.5,
       48. , 52.5, 53.5, 50. , 51.5, 51. , 54. , 57.5, 62. , 56.5, 63. ,
       68. , 61. , 64.5, 52.5, 54.5, 58. , 60. , 63.5, 64.5, 60. , 61. ,
       67. , 65.5, 74.5, 79.5, 80. , 81.5, 78.5, 75. , 78. , 74.5, 70. ,
       66.5, 74.5, 68. , 74. , 74.5, 59.5, 62.5, 67. , 73.5, 72.5, 65.5,
       68.5, 73.5, 69.5, 70.5, 74. , 77. , 74. , 79.5, 77. , 76. , 75.5,
       75. , 77. , 75. , 72. , 75. , 76. , 72.5, 69.5, 71. , 75. , 77.5,
       83. , 83. , 76.5, 68.5, 73. , 73. , 75. , 78. , 80.5, 83.5, 82.5,
       82. , 82.5, 78. , 76.5, 80.5, 84. , 88. , 84.5, 83. , 80.5, 82.5,
       85. , 77. , 78.5, 74.5, 74.5, 73.5, 73. , 74. , 76. , 79.5, 78. ,
       78.5, 79. , 80.5, 82.5, 83. , 88.5, 86. , 84.5, 82.5, 81. , 78.5,
       81. , 76.5, 79.5, 72. , 71.5, 78. , 77.5, 82.5, 81. , 80.5, 82.5,
       77.5, 81.5, 74. , 73.5, 70.5, 72.5, 74.5, 75.5, 78. , 80. , 83. ,
       82. , 75. , 70. , 73.5, 79. , 67.5, 67. , 68. , 76. , 72.5, 75. ,
       76. , 75.5, 75.5, 64.5, 62. , 64. , 69. , 62.5, 60.5, 57.5, 59. ,
       60. , 66. , 64.5, 60. , 64. , 66. , 63. , 58. , 55.5, 54.5, 59.5,
       60. , 54.5, 55. , 61. , 72. , 74. , 75. , 66. , 63. , 52. , 53. ,
       54.5, 47.5, 44.5, 47.5, 46.5, 51.5, 65. , 49. , 49. , 62. , 64.5,
       54. , 53. , 52. , 47. , 53.5, 54. , 48. , 52. , 43.5, 51. , 54. ,
       51.5, 53. , 55. , 54. , 50. , 38. , 38.5, 39. , 40. , 43. , 49.5,
       45. , 44.5, 45. , 55.5, 54. , 48. , 45.5, 44. , 43. , 43.5, 41.5,
       43. , 40. , 34. , 31.5, 31.5, 40. , 39. , 38. , 26.5, 22. , 31.5,
       44.5, 27. , 26.5, 35. , 43. , 42.5, 42.5, 43. , 41.5, 50. , 37. ,
       39.5, 36.5, 37.5])

In [92]:
# define the function f(t) = a*cos(2t*pi + b) + c
def f(t, a, b, c):
    return a*np.cos(2*t*np.pi + b) + c


data = pd.read_csv('weather_data_nyc_centralpark_2016(1).csv', usecols=['date', 'average temperature'],
                   parse_dates=['date'], index_col=['date'], squeeze=True)

keep = np.abs(data.values) < 90
filtered_data = data[keep]

# define the time as a fraction of the days since the first measurement
t = (filtered_data.index - filtered_data.index[0]).days

# define the parameters a, b, and c 
a = 1.0
b = 0.0
c = 0.0

f(t, a, b, c)

Float64Index([1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
              ...
              1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
             dtype='float64', name='date', length=366)

In [93]:
from scipy.optimize import curve_fit
a_bounds = (np.inf, -np.inf)
b_bounds = (-np.inf, -np.inf)
c_bounds = (-np.inf, -np.inf)
popt, _= curve_fit(f, t, data, p0=[10, 0, 10], bounds=(a_bounds, b_bounds, c_bounds))

ValueError: too many values to unpack (expected 2)